### ISSUE TITLE
Loading server translations on first start

### ISSUE THREAD

**Issue by toburger** [fulcrologic/fulcro-i18n#23]
I have a (RAD) application which supports two languages (German and Italian).
All the translations are provided by the [server](https://github.com/fulcrologic/fulcro-i18n/blob/main/I18N.adoc#17-responding-to-locale-loading-queries-on-your-server) 

Now when I initialize the application in the default language (:de) the client doesn't have any localized strings and it does not download the translations. When I switch the language to :it the localized Italian texts are downloaded. I wan't to initialize the app with the freshly downloaded localized strings from the server but I don't know if I am missing something.

I have followed every step. The only step I didn't understand was the step mentioned [here](https://github.com/fulcrologic/fulcro-i18n/blob/main/I18N.adoc#configuring-i18n):

> Your Root UI component MUST query for ::i18n/current-locale and should also set the initial locale in application state. The shared-fn extracts denormalized data from your UI root’s props. This also sets the "default" locale of your application.

Now I am not sure. Is this explained in the next step?

I've tried to leave out the :translations key from the line:

```clojure
::i18n/current-locale (comp/get-initial-state i18n/Locale {:locale :de :translations {}})
```

```clojure
::i18n/current-locale (comp/get-initial-state i18n/Locale {:locale :de})
```

This at least downloads the translations when I switch from :it back to :de again. If I provide a :translations map nothing will ever be translated to :de.

What also works is to set the :locale to :en. So that when i change the locale the translation get's downloaded. But thats not acceptable from a UX perspective.

I am sure I am missing something. I've also tried to execute the `(i18n/change-locale {:locale :de})` when I start the application (in the init function), but it didn't work.

----

Sorry, I am very new to the whole Fulcro (RAD) development experience so I may be making a very very silly mistake!

**Comment by toburger** [comment]
My "workaround" that seems to work is the following:

I set the default locale to :en (even the app is never using that locale):

```clojure
::i18n/current-locale (comp/get-initial-state i18n/Locale {:locale :en})
```

And in my init function the last thing I do is changing the locale to :de which triggers the loading of the translations from the server:
```clojure
(defn ^:export init []
  '...
  (comp/transact! app `[(i18n/change-locale {:locale :de})]))
```

**Comment by awkay** [comment]
Hi

The system is designed so you can use your "native language" as the strings in code. So, if your "native" is German, then I would expect that you would have used German strings in the code. It sounds like you used English instead.  If that is your preference, that's fine.

To load an alternate during startup (e.g. because of a detected locale in the browser) I would do the following:

1. Add a flag to the root component like :ui/ready?
2. When ready? is false, show a loader that is locale independent or that doesn't use the i18n system for translation (since it isn't done initializing yet). When it is true, show your app as normal.
3. Switch the locale on startup, as you're doing in your init, which will load the translations. You might just copy the content of the change-locale mutation so that you can hook into the `ok-action` to then set your root flag to ready.

If you switch to using German in your code, then no such step would be needed in your "normal" locale, since the code would already have those strings..but you always have the issue on load if you want to be locale sensitive from the start.
